services:
  nippo:
    build:
      context: ..
      dockerfile: Dockerfile.dev
    volumes:
      - ..:/nippo
      - /nippo/backend/node_modules
    ports:
      - '3000:3000'
    env_file:
      - ../.env
    command: npm run dev
