FROM node:22-alpine

WORKDIR /app/backend

RUN apk add --no-cache git bash curl postgresql-client github-cli openssh-client

COPY backend/package*.json ./
RUN npm install

EXPOSE 3000
CMD ["npm", "run", "dev"]